name: Scala CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
#  run_if:
#    if: startsWith(github.ref_name, 'feature/')
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Check branch name
        shell: bash
        run: |
          branch_name=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}")
          if [[ "${{ github.event_name }}" == 'pull_request' ]] && [[ $branch_name == feature/* || $branch_name == fix/* ]]; then
          echo "Branch name starts with 'feature/' or 'fix/'."
          elif [[ "${{ github.event_name }}" != 'pull_request' ]]; then
          echo "Skipping branch name check for merge operation."
          exit 0
          else
          echo "Branch name should start with 'feature/' or 'fix/'."
          exit 1
          fi

      - name: Run Scalafmt
        run: |
          mvn scalafmt:format

      - name: Build and Test
        run: |
          mvn clean compile test

      - name: List target directory
        run: ls -la target

      - name: List directory
        run: ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: runartifact
          path: target/dhrj.jar

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: runartifact

      - name: Build Tar File
        run: tar -czvf dhrj.tar.gz dhrj.jar


#
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: my-artifact-name
#          path: ./ci-cd/

