name: Scala CI

on:
  push:
    branches:
      - master
      - develop

jobs:
#  run_if:
#    if: startsWith(github.ref_name, 'feature/')
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          distribution: 'adopt'

      - name: Build and Test
        run: |
          mvn clean compile test

      - name: Run Scalafmt
        run: |
          mvn scalafmt:check
