name: Scala CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
#  run_if:
#    if: startsWith(github.ref_name, 'feature/')
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build and Test
        run: |
          mvn clean compile test

      - name: Run Scalafmt
        run: |
          mvn scalafmt:format

      - name: Check branch name
        shell: bash
        run: |
          branch_name=$(echo "${{ github.ref }}")
          if [[ ! "$branch_name" =~ ^(refs/heads/feature/|refs/heads/fix/) ]]; then
            echo "Branch name should start with 'feature/' or 'fix/'."
            exit 1
          fi
          
