name: Scala CI

on:
  push:
    branches:
      - master
      - develop

jobs:
#  run_if:
#    if: startsWith(github.ref_name, 'feature/')
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'oracle'

      - name: Build
        run: mvn --batch-mode -DskipTests package

